#tip内必须有一个且只能有一个{component}
#{pokemon}则由插件进行替换
#这里用的主要是pctools变量
tip: '&e%player_name% 孵化出了 {component}'
component:
  display: '&b&l%pctools_{pokemon}_localizedname%'
  hover:
    - "&b▣ 基本信息"
    - "&3属性: &7%pctools_{pokemon}_types% &f| &3蛋组: &7%pctools_{pokemon}_egggroup%"
    - "&3性格: &7%pctools_{pokemon}_nature% &f| &3特性: &7%pctools_{pokemon}_ability%"
    - "&3性别: &7%pctools_{pokemon}_gender% &f| &3道具: &7%pctools_{pokemon}_helditem%"
    - "&3闪光: &7%pctools_{pokemon}_shiny% &f| &3形态: &7%pctools_{pokemon}_form_localizedname%"
    - "&3体型: &7%pctools_{pokemon}_growth% &f| &3球种: &7%pctools_{pokemon}_caughtball%"
    - "&b▣ 种族信息&7 (总和：%pctools_{pokemon}_basetotal%)"
    - "&3血量: &7%pctools_{pokemon}_basestats_hp% &f| &3攻击: &7%pctools_{pokemon}_basestats_at% &f| &3防御: &7%pctools_{pokemon}_basestats_df%"
    - "&3特攻: &7%pctools_{pokemon}_basestats_sa% &f| &3特防: &7%pctools_{pokemon}_basestats_sd% &f| &3速度: &7%pctools_{pokemon}_basestats_sp%"
    - "&b▣ 个体信息&7 (%pctools_{pokemon}_ivstotal%/186)"
    - "&3血量: &7%pctools_{pokemon}_ivs_hp% &f| &3攻击: &7%pctools_{pokemon}_ivs_at% &f| &3防御: &7%pctools_{pokemon}_ivs_df%"
    - "&3特攻: &7%pctools_{pokemon}_ivs_sa% &f| &3特防: &7%pctools_{pokemon}_ivs_sd% &f| &3速度: &7%pctools_{pokemon}_ivs_sp%"
    - "&b▣ 努力信息&7 (%pctools_{pokemon}_evstotal%/510)"
    - "&3血量: &7%pctools_{pokemon}_evs_hp% &f| &3攻击: &7%pctools_{pokemon}_evs_at% &f| &3防御: &7%pctools_{pokemon}_evs_df%"
    - "&3特攻: &7%pctools_{pokemon}_evs_sa% &f| &3特防: &7%pctools_{pokemon}_evs_sd% &f| &3速度: &7%pctools_{pokemon}_evs_sp%"
    - "&b▣ 能力信息&7 (总和：%pctools_{pokemon}_statstotal%)"
    - "&3血量: &7%pctools_{pokemon}_stats_hp% &f| &3攻击: &7%pctools_{pokemon}_stats_at% &f| &3防御: &7%pctools_{pokemon}_stats_df%"
    - "&3特攻: &7%pctools_{pokemon}_stats_sa% &f| &3特防: &7%pctools_{pokemon}_stats_sd% &f| &3速度: &7%pctools_{pokemon}_stats_sp%"
    - "&b▣ 技能信息"
    - "&3技能: &7%pctools_{pokemon}_moveset_0% &f| &7%pctools_{pokemon}_moveset_1% &f| &7%pctools_{pokemon}_moveset_2% &f| &7%pctools_{pokemon}_moveset_3% "