#papi内可以自定义变量自定义的变量是json格式的可以自己用指令看看pokemon的json格式按照格式的地址来自定义
#支持PlaceholderAPI变量,papi内自定义的变量是用{}包裹,不过component不能再用,因为已经被占用了!
#tip内必须有一个且只能有一个{component}
tip: '&e%player_name% 孵化出了 {component}'
component:
  display: '&b&l{pokename}'
  hover:
    - '&e宝可梦: &a{pokename}'
    - '&e个体:'
    - '  &e生命: &a{ivhp}'

## 用指令获取一个基础实体的nbt数据，这数据会显示再后台
# ,可以全部复制然后粘贴到一个在线json格式化网站上，让他格式化
# 不然你有可能看不懂

##一下配置更具上面的说法搞到json数据后
# 自行配置
# 配置格式如下{中括号不需要带}
# [自定义的变量名]: '[再Json中的第一层数据索引名]'
papi:
  pokename: 'Name'
  ivhp: 'IVHP'
#配置好后如自定义变量名是ivhp,那么在最上面的配置信息的时候{ivhp}就是变量了